version: '2'

# Services to deploy:
#   - Jenkins
#   - Jenkins slave
# Network to deploy"
#   - dev-network 

services:
  jenkins:
    name: jenkins
    hostname: jenkins
    build:
      context: BUILD/jenkins
      args:
        JENKINS_VERSION: $JENKINS_VERSION
        JENKINS_APT_GET: $JENKINS_APT_GET
    ports:
      - "8080:8080"
      - "50000:50000"
      - "8083:8083"
    volumes:
      - DATA/JENKINS_HOME:/var/jenkins_home
    environment:
      JAVA_OPTS: "-Xmx512m -Xms512m"
      JENKINS_SLAVE_AGENT_PORT: 50000
      HTTP_PROXY: $HTTP_PROXY
      HTTPS_PROXY: $HTTPS_PROXY
      SOCKS_PROXY: $SOCKS_PROXY
    networks:
      - dev-network

  jenkins-slave:
    name: jenkins-slave
    hostname: jenkins-slave
    build:
      context: BUILD/jenkins-slave
      args:
        JENKINS_SLAVE_VERION: $JENKINS_SLAVE_VERSION  
    ports:
      - "50001:50001"
    volumes:
      - DATA/JENKINS_SLAVE_HOME:/var/jenkins_slave_home:rw      
    environment:
      JAVA_OPTS: "-Xmx512m -Xms512m"
      HTTP_PROXY: $HTTP_PROXY
      HTTPS_PROXY: $HTTPS_PROXY
      SOCKS_PROXY: $SOCKS_PROXY
    networks:
      - devops-network
    depends_on:
      - jenkins
      
networks:
  dev-network:
    driver: bridge
