version: '2'

# Services to deploy:
#   - Jenkins
#   - Jenkins slave
# Network to deploy"
#   - dev-network 

services:
  jenkins:
    build:
      context: BUILD/jenkins
      args:
        JENKINS_VERSION: $JENKINS_VERSION
        JENKINS_APT_GET: $JENKINS_APT_GET
    ports:
      - "8080:8080"
      - "50000:50000"
    volume:
      - v PV_DATA/JENKIN_HOME:/var/jenkins_home
    environment:
      JAVA_OPTS: "-Xmx512m -Xms512m"
      JENKINS_SLAVE_AGENT_PORT: 50000
    networks:
      - dev-network

  jenkins-slave:
    build:
      context: BUILD/jenkins-slave
      args:
        JENKINS_SLAVE_VERION: $JENKINS_SLAVE_VERSION  
    ports:
      - "50001:50001"
    environment:
      JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - devops-network
    depends_on:
      - $ENV_PREFIX-jenkins



networks:

  dev-network:
    driver: bridge
