version: '2'

# @Author: Vincent Pang / nzvincent@gmail.com
# Deploy services:
#   - Jenkins ( based on jenkins/jenkins:tls )
#   - Jenkins slave ( based on openJDK:stretch-11 )
# Deploy network"
#   - dev-network 

services:
  jenkins:
    hostname: jenkins
    build:
      context: BUILD/jenkins
      args:
        JENKINS_VERSION: $JENKINS_VERSION
        JENKINS_APT_GET: $JENKINS_APT_GET
    ports:
      - "8080:8080"
      - "50000:50000"
      - "8083:8083"
    volumes:
      - ./DATA/JENKINS_HOME:/var/jenkins_home
    environment:
      JAVA_OPTS: "-Xmx512m -Xms512m"
      JENKINS_SLAVE_AGENT_PORT: 50000
      HTTP_PROXY: $HTTP_PROXY
      HTTPS_PROXY: $HTTPS_PROXY
      SOCKS_PROXY: $SOCKS_PROXY
    networks:
      - dev-network

  jenkins-slave:
    hostname: jenkins-slave
    build:
      context: BUILD/jenkins-slave
      args:
        JENKINS_SLAVE_OPENJDK_VERSION: $JENKINS_SLAVE_OPENJDK_VERSION
        JENKINS_SLAVE_APT_GET: $JENKINS_SLAVE_APT_GET
    ports:
      - "50001:50001"
    volumes:
      - ./DATA/JENKINS_SLAVE_HOME:/home/jenkins     
    environment:
      JAVA_OPTS: "-Xmx512m -Xms512m"
      HTTP_PROXY: $HTTP_PROXY
      HTTPS_PROXY: $HTTPS_PROXY
      SOCKS_PROXY: $SOCKS_PROXY
    networks:
      - dev-network
    depends_on:
      - jenkins
      
networks:
  dev-network:
    driver: bridge
