---

- block:

  - name: Deploy Docker registry
    shell: | 
      docker run -d \
      --restart=always \
      --name registry \
      -v {{ registry_cert }}/certs:/certs \
      -e REGISTRY_HTTP_ADDR=0.0.0.0:443 \
      -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/kuber-registry.crt \
      -e REGISTRY_HTTP_TLS_KEY=/certs/kuber-registry.key \
      -p 443:443 \
      registry:2
 
