---

- block:

  - name: Create a directory if it does not exist
    file:
      path: {{ directories }}
      state: directory
      mode: '0755'
    vars:
      directories:
      - {{ registry_cert_dir }}
      - {{ registry_data_dir }}

  - name: Deploy Docker registry
    shell: | 
      docker run -d \
      --restart=always \
      --name registry \
      -v {{ registry_cert_dir }}:/certs \
      -e REGISTRY_HTTP_ADDR=0.0.0.0:443 \
      -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/kuber-registry.crt \
      -e REGISTRY_HTTP_TLS_KEY=/certs/kuber-registry.key \
      -p 443:443 \
      registry:2
 
