---

- block:

  - name: Create a directory if it does not exist
    file:
      path: "{{ item }}"
      state: directory
      mode: '0755'
    loop:
      - '{{ registry_cert_dir }}'
      - '{{ registry_data_dir }}'
    register: command_output  

 # - debug: msg="{{ command_output.stdout.split('\n') }}"  
  
  
  - name: Copy SSL key, cert to registry_cert_dir
    copy:
      src: "{{ item.source }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: "{{ item.mode }}"
    loop:
      - { source: '{{ registry_ssl_crt }}' , dest: '{{ registry_cert_dir }}/{{ registry_ssl_crt }}', mode: '0640' }
      - { source: '{{ registry_ssl_key }}' , dest: '{{ registry_cert_dir }}/{{ registry_ssl_key }}', mode: '0640' }   


  - name: Deploy Docker registry
    shell: | 
      docker run -d \
      --restart=always \
      --name registry \
      -v {{ registry_cert_dir }}:/certs \
      -e REGISTRY_HTTP_ADDR=0.0.0.0:443 \
      -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/{{ registry_ssl_crt }} \
      -e REGISTRY_HTTP_TLS_KEY=/certs/{{ registry_ssl_key }} \
      -p 443:443 \
      registry:2
 
