# Install Kubernetes kubeadm / kubectl / kubelet 
#   - kuber-master
#   - kuber-worker
# Other references:
#   - https://www.linuxtechi.com/install-kubernetes-1-7-centos7-rhel7/
#   - https://www.howtoforge.com/tutorial/centos-kubernetes-docker-cluster/
#   - https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/
---

- hosts: all

  tasks:

  #================================================================================================
  - name: Install Kubernetes base system
  #================================================================================================
    include_role:
      name: install-kubernetes
  
  become: yes
  become_user: root
  become_method: sudo 
