---

- hosts: all

  tasks:

  #================================================================================================
  - name: Install Kubernetes base system
  #================================================================================================
    include_role:
      name: install-base-system
      
  become: yes
  become_user: root
  become_method: sudo