---

- hosts: all

  tasks:

  #================================================================================================
  - name: Install Docker registry
  #================================================================================================
    include_role:
      name: install-docker-registry
  
  become: yes
  become_user: root
  become_method: sudo 
