# Deploy docker private registry to kuber-extra-services as local-registry:443
# Example: - docker tag IMAGE_ID local-registry:443/nginx-latest
#          - docker push local-registry:443/nginx-latest 
#          - docker run -it --name web -host web local-registry:443/nginx-latest /bin/sh
---

- hosts: all

  tasks:

  #================================================================================================
  - name: Install Docker registry
  #================================================================================================
    include_role:
      name: install-docker-registry
  
  become: yes
  become_user: root
  become_method: sudo 
