---

- block:

  - name: Add registry DNS to /etc/hosts
    lineinfile:
      path: /etc/hosts
      line: "{{ registry_host_ip }} {{ item }}"
      state: present
    loop: "{{ registry_hostname_alias }}"
    
  - name: Copy daemon.json with registry 
    copy:
      src: daemon.json
      dest: /etc/docker/daemon.json
      owner: root
      group: root
      mode: 0644
      backup: yes 
    notify:
    - Restart Docker
    
  
  
