---
# @Author: Vincent Pang / nzvincent@gmail.com

- hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:
  
  ############################
  # Block: for Debian / Ubuntu
  ############################
  - name: For Debian and Ubuntu Only  
    block:
    
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
        update_cache: yes
        
    - name: Install packages
      apt: 
        name: "{{ item }}" 
        state: latest
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - libxss1
        - aptitude

    - name: Add Docker’s official GPG key - old school way
      shell: |
        curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -

    - name: Add Docker respository - old school way
      shell: |
        add-apt-repository \
           "deb [arch=amd64] https://download.docker.com/linux/debian \
           $(lsb_release -cs) \
           stable"
        
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
        update_cache: yes
        
    - name: Install packages
      apt: 
        name: "{{ item }}" 
        state: latest
      loop:
        - docker-ce 
        - docker-ce-cli 
        - containerd.io

    - name: Enable and start up Docker service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Verify Docker installation
      shell: |
        docker --version
        docker images
      register: command_output

    - debug: msg="{{ command_output.stdout.split("\n") }}"    
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' 
