---

- hosts: all
  become: true
  user: root
  connection: ssh 

  tasks:
  
  ############################
  # Block: for Debian / Ubuntu
  ############################
  - block:
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'  

      - name: Update all packages to the latest version
        apt:
          upgrade: dist

      - name: Install packages
        apt: 
          name: {{ item }} 
          state: latest
        loop:
         - apt-transport-https
         - ca-certificates
         - curl
         - gnupg-agent
         - software-properties-common

      - name: Add Docker’s official GPG key - old school way
        shell: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

      - name: Add Docker respository - old school way
        shell: |
          add-apt-repository \
          "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) \
          stable"

      - name: Install Docker - old school bash method
        shell: |
          apt-get -y update && \ 
          apt-get -y install docker-ce docker-ce-cli containerd.io

      - name: Enable and start up Docker service
        service:
          name: httpd
          state: started
          enabled: yes

      - name: Verify Docker installation
        shell: |
          docker --version
          docker images
        register: command_output

      - debug: msg:"{{ command_output.stdout.split("\n") }}"    
