version: '2'

services:

  homebrew-registry:
    build:
      context: BUILD/homebrew-registry/
      args:
        REGISTRY_VERSION: $REGISTRY_VERSION
    ports:
      - "5000:5000"
    environment:
      -e REGISTRY_HTTP_TLS_CERTIFICATE=$REGISTRY_TLS_CERT
      -e REGISTRY_HTTP_TLS_KEY=$REGISTRY_TLS_KEY
    volume:
      - $REGISTRY_CERT_VOL:/cert
      - $REGISTRY_STORAGE_VOL:/var/lib/registry
