#!/bin/bash

# SMTP relay host
[[ -e $RELAYHOST ]] && POSTFIX_RELAYHOST=$RELAYHOST || POSTFIX_RELAYHOST="smtp.gmail.com"
[[ -e $RELAYHOST_PORT ]] && POSTFIX_RELAYHOST_PORT=$RELAYHOST_PORT || POSTFIX_RELAYHOST_PORT="587"

# SMTP login
[[ -e $RELAYHOST_USER ]] && POSTFIX_RELAYHOST_USER=$RELAYHOST_USER || POSTFIX_RELAYHOST_USER="your-gmail-user"
[[ -e $RELAYHOST_PASSWORD ]] && POSTFIX_RELAYHOST_PASSWORD=$RELAYHOST_PASSWORD || POSTFIX_RELAYHOST_PASSWORD="12345678"






