#!/bin/bash

[[ -e $RELAYHOST ]] && POSTFIX_RELAYHOST=$RELAYHOST || POSTFIX_RELAYHOST="smtp.gmail.com"

[[ -e $RELAYHOST_PORT ]] && POSTFIX_RELAYHOST_PORT=$RELAYHOST_PORT || POSTFIX_RELAYHOST_PORT="587"



