pipeline{
  agent any
  
  stages{
    stage("Building docker image"){
      steps{
        sh 'echo "building docker image"'
        def testImage = docker.build("alpine-postfix:homebrew", "./docker/gmail-postfix-relay/Dockerfile")
      }
    }
    
  
  }
}
