pipeline{
  agent any
  
  stages{
    stage("Building docker image"){
       agent {
        def alpine-postfix = docker.build("alpine-postfix:homebrew", "./docker/gmail-postfix-relay/Dockerfile")
      }
    }
    
  
  }
}
