pipeline {
    agent { 
        dockerfile {
            filename './docker/gmail-postfix-relay/'
            dir 'build'
            additionalBuildArgs  '--build-arg version=1.0.2'
            args '-v /tmp:/tmp'
        }
    }
           
    stages {
        stage('Test') {
            steps {
                sh 'node --version'
                sh 'svn --version'
            }
        }
    }
}
