---
#@Original ref: https://blog.confirm.ch/adding-a-new-trusted-certificate-authority/

- hosts:  all
 
  vars:
    ca_path_debian: /usr/local/share/ca-certificates
    ca_path:
      RedHat:
        6: /usr/local/share/ca-certificates
        7: /etc/pki/ca-trust/source/anchors
      Centos:
        6: /usr/local/share/ca-certificates
        7: /etc/pki/ca-trust/source/anchors        
      Debian:
        7: '{{ ca_path_debian }}'
        8: '{{ ca_path_debian }}'
        9: '{{ ca_path_debian }}'   
       Ubuntu:
        14: '{{ ca_path_debian }}'
        16: '{{ ca_path_debian }}'
        18: '{{ ca_path_debian }}' 
 
  tasks:
  - name: install ca package on rhel systems
    yum:
      name: ca-certificates
      state: present
    when: ansible_os_family == "RedHat"
 
  - name: install ca package on debian systems
    apt:
      name: ca-certificates
      state: present
      update_cache: yes
    when: ansible_os_family == "Debian"
 
  - name: enable dynamic ca configuration on rhel6
    shell: /bin/update-ca-trust enable
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 6
 
  - name: copy certificate authority to trusted ca path of the os
    copy:
      src: '{{ item }}'
      dest: '{{ ca_path[ansible_os_family][ansible_distribution_major_version|int] }}/'
      owner: root
      group: root
      mode: 0644
    with_fileglob:
      - files/ca/*
    notify:
      - update trusted ca debian
      - update trusted ca redhat
 
  handlers:
  - name: update trusted ca debian
    shell: /usr/sbin/update-ca-certificates
    when: ansible_os_family == "Debian"
 
  - name: update trusted ca redhat
    shell: /bin/update-ca-trust
    when: ansible_os_family == "RedHat"
 
  sudo: yes
