---

- block:

  #####################################################
  # Install Docker private registry
  #####################################################

  - name: Prepare persistent storage
    file:

  - name: Install Docker private registry
    docker_compose:
      project_src: homebrew-registry.yml
      state: present

  - debug:
      var: output
