---

- block:

  #####################################################
  # Install NFS server
  #####################################################

  - name: Install Docker private registry
    docker_compose:
      project_src: homebrew-registry
      state: present

  - debug:
      var: output
