---

- block:

  - name: Reload NFS
    shell: 'exportfs -ra'
    
  - name: Restart Docker
    shell: 'servie docker restart'
    register: command_output
    
  - name: Reboot OS
    reboot:
    register: command_output
        
