# @Author: nzvincent@gmail.com | Vincent Pang
# Reference: https://docs.okd.io/latest/install_config/storage_examples/shared_storage.html
# PODS -> PVC -> PV -> NFS-SERVER

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv 
spec:
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /data/NFS_EXPORT/web-proxy-nfs-pod/apache2 
    server: $NFS_SERVER_IP
    readOnly: false
    
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc  
spec:
  accessModes:
  - ReadWriteMany      
  resources:
     requests:
       storage: 1Gi    
       
       
---

apiVersion: v1
kind: Pod
metadata:
  name: web-proxy-nfs-pod 
  labels:
    name: web-proxy-nfs-pod
spec:
  containers:
    - name: web-proxy-nfs-pod
      image: homebrew-image/web-proxy-nfs-pod
      ports:
        - name: web
          containerPort: 80
      volumeMounts:
        - name: nfsvol 
          mountPath: /etc/apache2
  securityContext:
      supplementalGroups: [100003] 
      privileged: false
  volumes:
    - name: nfsvol
      persistentVolumeClaim:
        claimName: nfs-pvc 


