# @Author: nzvincent@gmail.com | Vincent Pang
# Reference: https://docs.okd.io/latest/install_config/storage_examples/shared_storage.html

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv 
spec:
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /data/NFS_EXPORT 
    server: $NFS_SERVER_IP
    readOnly: false

