#!/bin/bash 

# Jenkins bash script

# One off download and install
#git clone https://github.com/Neilpang/acme.sh.git
#cd ./acme.sh
#./acme.sh --install

CMD_ACME='~/.acme.sh/acme.sh'

#~/.acme.sh/acme.sh --register-account
#~/.acme.sh/acme.sh --update-account --accountemail nzvincent@gmail.com

# Use your digitalOcean API key, so that acme.sh can add DNS txt entry to verify you are the owner of the domain.
export DO_API_KEY=__________DIGITALOCEAN_API_KEY__________________________

# Reference
# https://0wned.it/2018/10/04/using-acme-sh-for-certificate-management/
#~/.acme.sh/acme.sh --test --dns dns_dgon --cert-home /etc/certs --renew-hook "service apache2 reload" --issue -d www.domain.com -d sub1.

DOMAIN=www.example.com

# First time only --standalone parameter allows to generate certificate on non httpd machines.
#~/.acme.sh/acme.sh --dns dns_dgon --standalone --issue -d ${DOMAIN}
# Renewal 
# ~/.acme.sh/acme.sh --renew-all 
~/.acme.sh/acme.sh --renew ${DOMAIN}

HTTPD_SERVER=example.com
HTTPD_USER=root

# Copy cert to /etc/apache2/SSL

ssh ${HTTPD_USER}@${HTTPD_SERVER} <<'ENDSSH'
TS=`date '+%Y%m%d%H%M%S'`
DOMAIN=www.example.com
cd /etc/apache2/SSL/
cp -p ${DOMAIN}.cer  ${DOMAIN}.cer.${TS}
cp -p ${DOMAIN}.key  ${DOMAIN}.key.${TS}
cp -p ${DOMAIN}-fullchain.cer  ${DOMAIN}-fullchain.cer.${TS}
ENDSSH

# Transfer files to remote server
scp ~/.acme.sh/${DOMAIN}/${DOMAIN}.cer ${HTTPD_USER}@${HTTPD_SERVER}:/etc/apache2/SSL/ 
scp ~/.acme.sh/${DOMAIN}/${DOMAIN}.key ${HTTPD_USER}@${HTTPD_SERVER}:/etc/apache2/SSL/ 
scp ~/.acme.sh/${DOMAIN}/${DOMAIN}-fullchain.cer ${HTTPD_USER}@${HTTPD_SERVER}:/etc/apache2/SSL/${DOMAIN}-fullchain.cer

# Secure remote files permissions and reload apache
ssh ${HTTPD_USER}@${HTTPD_SERVER} <<'ENDSSH'
chmod 644 /etc/apache2/SSL/*.cer
chmod 640 /etc/apache2/SSL/*.key
/etc/init.d/apache2 reload
ENDSSH









