---

- name: Playbook to renew Let's encrypt signed SSL
  hosts: all
  serial: 2
  tasks:

  - name: Check if a certificate is currently still valid, ignoring failures
    openssl_certificate:
      path: {{ domain_ssl_path }}
      provider: assertonly
      has_expired: no
    ignore_errors: yes
    register: validity_check
    delegate_to:  127.0.0.1
 
   - debug: msg="{{ validity_check.strout }}"

  - name: Renew SSL using Let's Encrypt signed Certificates
  
  - name: Spin up Docker container with persistent volume
  docker:
    name: {{ acme_name }} 
    image: {{ acme_image }}
    state: create
    pull: always
    devices:
    - "{{ key_store_dir }}/{{ host_domain }}:/DATA"
    ports:
    - "9999:9999"
    extra_hosts:
    env:
      DNSs={{ wildcard_host_domain }}, {{ san_host_domain }}
    delegate_to: 127.0.0.1
 
  
  
      
  
